ARG VARIANT=3.13-slim-bookworm
FROM devcontainer-python:3.13-slim-bookworm

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
    apt-get install -y \
      openssh-client \
      sshpass && \
    apt autoremove -y && \
    apt clean -y && \
    rm -rf /var/lib/apt/lists/*

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

RUN mkdir /scripts
RUN mkdir /config 

COPY ./ansible.cfg /config
COPY ./hosts.example.yaml /config
COPY ./bootstrap-new-playbook.sh /scripts

RUN chmod +x /scripts/bootstrap-new-playbook.sh

RUN pip install pip --upgrade

# --user configures for the current user instead of root: "pip install --user ansible"
RUN pip install ansible
RUN pip install ansible-lint

# ENV PATH="/home/appuser/.local/bin:${PATH}"

# Additional Ansible configuration
RUN mkdir -p /root/.ssh && \
    mkdir -p /root/.ansible/roles /root/.ansible/tmp 

# Resolves ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
ENV LC_ALL="C.UTF-8"
